#!/bin/bash
# Copyright 2021-2025 Google LLC.
# SPDX-License-Identifier: MIT

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -x

mount -n -t proc -o nosuid,noexec,nodev proc /proc/
mount -n -o remount,rw /

mkdir -p /dev /sys /etc

mount -n -t sysfs -o nosuid,noexec,nodev sys /sys
mount -n -t tmpfs -o mode=1777 tmpfs /tmp

cd /root && exec setsid bash -l 0<>"/dev/ttyS0" 1>&0 2>&0
