apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: uiuctf-egress-k8s-api
spec:
  podSelector:
    matchLabels:
      uiuctf-egress: k8s-api
  egress:
    - to:
        - ipBlock:
            cidr: 172.16.0.34/32
      ports:
        - protocol: TCP
          port: 443
  policyTypes:
    - Egress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instancer-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instancer-manager-clusterroles
rules:
  - apiGroups: ["*"]
    resources:
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instancer-manager
subjects:
  - kind: ServiceAccount
    name: instancer-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: instancer-manager-clusterroles
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instancer
  namespace: default
  labels:
    app: instancer
spec:
  selector:
    matchLabels:
      app: instancer
  template:
    metadata:
      labels:
        app: instancer
        uiuctf-egress: k8s-api
    spec:
      containers:
        - name: instancer
          image: us-central1-docker.pkg.dev/dotted-forest-314903/uiuctf-2025/instancer-instancer:4dcd8b1c58f080149608a4942b39b4e298dca676bbc9df068a99f3a6d20a8adf
          ports:
            - containerPort: 1337
          envFrom:
            - secretRef:
                name: instancer-secrets
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: instance-templates-volume
              mountPath: /etc/instance-templates
      serviceAccountName: instancer-manager
      volumes:
        - name: instance-templates-volume
          configMap:
            name: instance-templates
---
apiVersion: v1
kind: Service
metadata:
  name: instancer
  namespace: default
  labels:
    app: instancer
spec:
  selector:
    app: instancer
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: ClusterIP
