apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: CHALLENGE_NAME-instancer
  labels:
    app: CHALLENGE_NAME-instancer
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`CHALLENGE_NAME.chal.uiuc.tf`)
    kind: Rule
    services:
    - name: instancer
      port: 1337
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Namespace
metadata:
  name: CHALLENGE_NAME-managed
  labels:
    name: CHALLENGE_NAME-managed
    uiuctf-namespace: instancer-managed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: CHALLENGE_NAME-manager-role
  namespace: CHALLENGE_NAME-managed
rules:
  - apiGroups: ["*"]
    resources:
      - jobs
      - pods
      - services
      - ingressroutes
      - ingressroutetcps
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - watch
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: CHALLENGE_NAME-manager
  namespace: CHALLENGE_NAME-managed
subjects:
  - kind: ServiceAccount
    name: instancer-manager
    namespace: default
roleRef:
  kind: Role
  name: CHALLENGE_NAME-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-internal
  namespace: CHALLENGE_NAME-managed
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 0.0.0.0/8
              - 10.0.0.0/8
              - 100.64.0.0/10
              - 127.0.0.0/8
              - 169.254.0.0/16
              - 172.16.0.0/12
              - 192.0.0.0/24
              - 192.0.2.0/24
              - 192.88.99.0/24
              - 192.168.0.0/16
              - 198.18.0.0/15
              - 198.51.100.0/24
              - 203.0.113.0/24
              - 224.0.0.0/4
              - 240.0.0.0/4
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: CHALLENGE_NAME-managed
spec:
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
  podSelector: {}
  policyTypes:
    - Egress
