<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\spaceship_-_cb2.glb --types
Author: Lezalit (https://sketchfab.com/Lezalit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-cb2-b9708d29e85746c891b48075a8a1e70a
Title: SPACESHIP - CB2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  ref = new Group()

  type ActionName = 'FLY'
  type GLTFResult = {
    nodes: {
      Cube030_Material001_0: THREE.Mesh
      Cylinder011_Material001_0: THREE.Mesh
      Cube033_Material001_0: THREE.Mesh
      Cylinder010_Material001_0: THREE.Mesh
      Cylinder001_Material001_0: THREE.Mesh
      Cylinder003_Material001_0: THREE.Mesh
      Cylinder005_Material001_0: THREE.Mesh
      Cube018_Material001_0: THREE.Mesh
      Cylinder002_Material001_0: THREE.Mesh
      Cylinder006_Material001_0: THREE.Mesh
      Cube_Material001_0: THREE.Mesh
      _rootJoint: THREE.Bone
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/spaceship_-_cb2.glb')

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <T.Group
          name="696729a048454f61a4438ed9262cac38fbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group
                name="Radial_Empty"
                position={[-2701.94, 0, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <T.Group
                name="Armature001"
                position={[-2053.32, -763.77, -298.62]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <T.Group name="Object_6">
                  <T is={gltf.nodes._rootJoint} />
                </T.Group>
              </T.Group>
              <T.Group
                name="Radial_Empty004"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
