<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\space_ship.glb --root /models/ --types
Author: Ingoldt (https://sketchfab.com/nilsolejonack)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-ship-72cf562524d944c7a66406eb3901412e
Title: Space Ship
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Boster_Texture_Booster_0: THREE.Mesh
      Space_Ship_Texture_Space_SHip_0: THREE.Mesh
      Troop_Container_Texture_Container_0: THREE.Mesh
      Wings_Texture_Wings_0: THREE.Mesh
    }
    materials: {
      Booster: THREE.MeshStandardMaterial
      Space_SHip: THREE.MeshStandardMaterial
      Container: THREE.MeshStandardMaterial
      Wings: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/space_ship.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Mesh
        geometry={gltf.nodes.Boster_Texture_Booster_0.geometry}
        material={gltf.materials.Booster}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Mesh
        geometry={gltf.nodes.Space_Ship_Texture_Space_SHip_0.geometry}
        material={gltf.materials.Space_SHip}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Mesh
        geometry={gltf.nodes.Troop_Container_Texture_Container_0.geometry}
        material={gltf.materials.Container}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Mesh
        geometry={gltf.nodes.Wings_Texture_Wings_0.geometry}
        material={gltf.materials.Wings}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
