apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: ai-clippy
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 3000
  healthcheck:
    enabled: false
  image: us-central1-docker.pkg.dev/dotted-forest-314903/uiuctf-2025/ai-clippy-challenge:a615073a82aed062729aa3b17edd156ead1c1c55b1fa8884a7405ecd95a7b997
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: secrets
                mountPath: /chroot/app/.env.local
                subPath: .env.local
            resources:
              limits:
                memory: 4Gi
              requests:
                memory: 3Gi
        volumes:
          - name: secrets
            secret:
              secretName: ai-clippy-secrets
  horizontalPodAutoscalerSpec:
    maxReplicas: 3
    minReplicas: 2
    targetCPUUtilizationPercentage: 60
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ai-clippy
  labels:
    app: ai-clippy
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`ai-clippy.chal.uiuc.tf`)
      kind: Rule
      services:
        - name: ai-clippy
          port: 1337
  tls:
    secretName: tls-cert
