apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: qas
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 1337
  healthcheck:
    enabled: true
    image: us-central1-docker.pkg.dev/dotted-forest-314903/uiuctf-2025/qas-healthcheck:2bf5d537ae62b9f320bf4b0dc948e56d8bf51e42e0e19b315262e693ae971aa4
  image: us-central1-docker.pkg.dev/dotted-forest-314903/uiuctf-2025/qas-challenge:ea7344243b48cc188d1467899137af706063c4421610f0a349304649e5ab5b22
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: qas
  labels:
    app: qas
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`qas.chal.uiuc.tf`)
      services:
        - name: qas
          port: 1337
  tls:
    secretName: tls-cert
